base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/vg/vg1.0.yaml",
]

run:
  batch_size_eval: 32
  output_dir: "output/eval/vg1.0"
  eval_dataset_name: "vg1.0"
