base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/vg/vg_reg.yaml",
]

model:
  tag_thr: 0.8

run:
  batch_size_eval: 32
  output_dir: "output/eval/vg_reg"
  eval_dataset_name: "vg_reg"
