base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/vg/vgcoco.yaml",
]

run:
  batch_size_eval: 32
  output_dir: "output/eval/vgcoco"
  eval_dataset_name: "vgcoco"
