base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/refcoco/refcocog.yaml",
]

model:
  tag_thr: 0.76

run:
  output_dir: "output/eval/refcocog_reg"
  eval_dataset_name: "refcocog"
