base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/vg_pred_bboxes/vg1.2.yaml",
]

run:
  batch_size_eval: 32
  output_dir: "output/eval/vg1.2_grit"
  eval_dataset_name: "vg1.2"
