base: ["configs/base/runs/eval.yaml",
       "configs/base/models/dynrefer_flant5xl.yaml",
       "configs/base/datasets/ovad/ovad.yaml",
]

run:
  output_dir: "output/eval/ovad"
  eval_dataset_name: "ovad"
